get_all_users=SELECT * FROM users.app_users;

save_transactions=INSERT INTO `accounts`.`transactions` (`transaction_ref_num`, `account_id`, `transaction_date`, `description`, `credit_txn`, `amount`, `reversal_txn`) VALUES (?, ?, ?, ?, ?, ?, ?);
delete_transactions=DELETE from `accounts`.`transactions` where account_id = ?;

save_expense_details=INSERT INTO `accounts`.`expense_details` (`transaction_id`, `category`) VALUES (?, ?);