get_all_users=SELECT * FROM users.app_users;

save_transactions=INSERT INTO `accounts`.`transactions` (`transaction_ref_num`, `account_id`, `transaction_date`, `description`, `credit_txn`, `amount`, `reversal_txn`) VALUES (?, ?, ?, ?, ?, ?, ?);
delete_transactions=DELETE from `accounts`.`transactions` where account_id = ?;

get_category_wise_expenses=SELECT c.category_name, COUNT(ed.transaction_id) AS num_expenses, SUM(t.amount) AS total_expenditure FROM transactions t INNER JOIN expense_details ed ON t.account_id = :accountId AND ed.transaction_id = t.transaction_id AND (t.transaction_date between :fromDate and :toDate) INNER JOIN categories c ON c.category_id = ed.category_id GROUP BY c.category_id;