server.error.whitelabel.enabled=false

file.storage.destination=/home/life/code/accounting/storage

spreadsheet.allowed.extensions=xls,xlsx

spring.datasource.url=jdbc:mysql://localhost:3306/accounts
spring.datasource.username=shriram
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.devtools.restart.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

entity.transaction.batch-size=10
mysql.date.format=yyyy-MM-dd

# Log Hibernate messages at the ERROR level
log4j.logger.org.hibernate=ERROR, file

# Configure the appender to write logs to a file
log4j.appender.file=org.apache.log4j.FileAppender
log4j.appender.file.File=hibernate.log
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

user.timezone=IST