file.storage.destination=/home/life/code/accounting/storage
spreadsheet.allowed.extensions=xls,xlsx
spring.datasource.url=jdbc:mysql://localhost:3306/accounts
spring.datasource.username=shriram
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
