server.port=8080
server.error.whitelabel.enabled=false

jakarta.persistence.jdbc.url=jdbc:mysql://localhost:3306/userdb

spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.devtools.restart.enabled=false
spring.datasource.initialization-mode=always

authDatasource.url=jdbc:mysql://localhost:3306/authdb
authDatasource.username=root
authDatasource.password=root1234
authDatasource.driver-class-name=com.mysql.cj.jdbc.Driver


session.auth-token=sessionToken
session.cookie.domain=localhost
session.cookie.max-age=86400
session.post-login.routes=
session.expiry.seconds=3600
cors.allowed.origins=http://localhost:3000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Log Hibernate messages at the ERROR level
log4j.logger.org.hibernate=ERROR, file
log4j.logger.com.accounting=INFO, file

# Configure the appender to write logs to a file
log4j.appender.file=org.apache.log4j.FileAppender
log4j.appender.file.File=hibernate.log
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

user.timezone=IST

password.encryption.rounds=12

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nshriram4895@gmail.com
spring.mail.password=gigp hgzo lxow rzyz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

registration.token.mail.from-address=nshriram4895@gmail.com
registration.token.mail.subject=Verify your account on local.finfree.com
registration.token.mail.body=Hello {userName} !\n\n Greetings from local.finfree.com! Use the following OTP to register:\n {token}
registration.token.mail.num-digits-token=6
registration.token.mail.expiry-minutes=10

forgot-password.token.mail.from-address=nshriram4895@gmail.com
forgot-password.token.mail.subject=Reset your password on local.finfree.com
forgot-password.token.mail.body=Hello {userName} !\n\n Use the following OTP to reset your password:\n {token}
forgot-password.token.mail.num-digits-token=6
forgot-password.token.mail.expiry-minutes=10

account-number.default.length=10

# Hibernate Properties
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true