server.port=8080
server.error.whitelabel.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.devtools.restart.enabled=false
spring.datasource.initialization-mode=always

authDatasource.url=jdbc:mysql://localhost:3306/authdb
authDatasource.username=root
authDatasource.password=root

session.auth-token=sessionToken
session.cookie.domain=localhost
session.cookie.max-age=86400
session.post-login.routes=
session.expiry.seconds=3600
cors.allowed.origins=http://localhost:3000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Log Hibernate messages at the ERROR level
log4j.logger.org.hibernate=ERROR, file
log4j.logger.com.accounting=INFO, file

# Configure the appender to write logs to a file
log4j.appender.file=org.apache.log4j.FileAppender
log4j.appender.file.File=hibernate.log
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

user.timezone=IST

password.encryption.rounds=12