create schema if not exists userdb charset utf8mb4 collate utf8mb4_unicode_ci;
DROP table if exists userdb.users;
CREATE TABLE userdb.users (
    user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    login_id VARCHAR(100) UNIQUE KEY,
    `name` VARCHAR(100),
    `password` VARCHAR(100),
    email_id VARCHAR(400)
)  CHARSET=UTF8MB4 , COLLATE = UTF8MB4_UNICODE_CI;

drop table if exists userdb.SPRING_SESSION;
CREATE TABLE if not exists userdb.SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    PRIMARY KEY (PRIMARY_ID)
);

drop table if exists userdb.SPRING_SESSION_ATTRIBUTES;
CREATE TABLE if not exists userdb.SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);